### ISSUE TITLE
the cyber 250x122 theme actually uses 320x240 images, making it overflow on a waveshare 250x122 eink screen

### ISSUE THREAD

**Issue by formula-spectre** [V0r-T3x/Fancygotchi_themes#1]
I partially solved the issue by scaling all the images that the config-{h,v}.toml call, but i'm stuck on scaling the actual faces. if you can give me a hint on how to do that I might open a pr fixing this!

**Comment by V0r-T3x** [comment]
is it what you are searching?

[change-the-pwnagotchi-face-with-image](https://github.com/V0r-T3x/pwnagotchi-fancygotchi?tab=readme-ov-file#to-change-the-pwnagotchi-face-with-image)

**Comment by V0r-T3x** [comment]
I always used the same avatar image, and I resized them with the `zoom` value. I dont know if the result can be ok at this size.

**Comment by formula-spectre** [comment]
huh, `ui.zoom`?

**Comment by formula-spectre** [comment]
also, is there a particular reason why fancytools is not compatible with Jayofelony's image? is it only fancytools or I can use the themes on their image?

**Comment by V0r-T3x** [comment]
Here, the list of all components value. You can search for 'zoom'. This is an option inside the theme config file. 

https://github.com/V0r-T3x/pwnagotchi-fancygotchi

The line to adjust in an example config file:

https://github.com/V0r-T3x/fancygotchi_themes/blob/main/themes%2Fpwnachu%2F250x122%2Fconfig-h.toml#L55

Jay modified the files used by Fancygotchi. If those files are replaced this is breaking things. I'm working to make a patcher instead of the file replacement. 

I can't know exactly what will change in the future into any of this file. So I can point you to the last problem I saw, but this can be different in his future images. I need to have a better approach for the potential future innovations.

**Comment by formula-spectre** [comment]
I tried to put various values in zoom, even negative, in the sections 
`[theme.main_elements.face.faces]` and `[theme.main_elements.face.faces]`, but the face did not scale; for record, I tried `0.5 0.1 -5 -5.0 -0.5` and some other combinations. am I doing this wrong?

**Comment by V0r-T3x** [comment]
Ok I thought you tried to use custom images to change the pwnagotchi face.

The face is linked to the "huge" font. So if you need to make it bigger you can change the 4th value from the size font list.

https://github.com/V0r-T3x/fancygotchi_themes/blob/main/themes%2Fcyber%2F250x122%2F200x200%2Fconfig-h.toml#L12

This one is set to 55. Try to change this value in your theme config file.
